POST http://localhost:3000/twitter-client
Content-Type: application/json

{ 
    "prompt": "@TestBots28 tip 0.4016 usdc to B3oQQv6K3VX9wjMkWd426ykHKYamqQvTXuwwLFMSVav3 on solana"
}

# GET http://localhost:3000
# Content-Type: application/json

# # {
# #     "prompt": "Swap 1 usdc on solana to usdc on base"
# # }